#  -*- coding: utf-8 -*-

ODRL_CLASSES_MAPPINGS = {
    "0": 1,
    "O": 1,
    "_": 1,
    "B-PERMISSION": 2,
    "B-PERMITS": 2,
    "I-PERMISSION": 3,
    "I-PERMITS": 3,
    "B-PROHIBITION": 4,
    "B-PROHIBITS": 4,
    "I-PROHIBITION": 5,
    "I-PROHIBITS": 5,
    "B-DUTY": 6,
    "B-REQUIRES": 6,
    "I-DUTY": 7,
    "I-REQUIRES": 7
}

ODRL_ACTIONS_MAPPINGS = {
    "ATTACHPOLICY": 1,
    "NOTICE": 1,
    "ATTACHSOURCE": 2,
    "ATTRIBUTE": 3,
    "ATTRIBUTION": 3,
    "COMMERCIALIZE": 4,
    "COMMERCIALUSE": 4,
    "COPY": 5,
    "REPRODUCE": 5,
    "REPRODUCTION": 5,
    "DERIVATIVEWORKS": 6,
    "DERIVE": 6,
    "MODIFY": 6,
    "DISTRIBUTE": 7,
    "DISTRIBUTION": 7,
    "SHARE": 7,
    "SHARING": 7,
    "READ": 8,
    "SELL": 9,
    "SHAREALIKE": 10,
}

NLL2RDF_CLASSES_MAPPINGS = {
    (1, 0): 0,
    (2, 4): 1,
    (3, 4): 2,
    (2, 5): 3,
    (3, 5): 4,
    (2, 6): 5,
    (3, 6): 6,
    (2, 7): 7,
    (3, 7): 8,
    (2, 8): 9,
    (3, 8): 10,
    (2, 9): 11,
    (3, 9): 12,
    (4, 4): 13,
    (5, 4): 14,
    (4, 6): 15,
    (5, 6): 16,
    (4, 7): 17,
    (5, 7): 18,
    (6, 1): 19,
    (7, 1): 20,
    (6, 2): 21,
    (7, 2): 22,
    (6, 3): 23,
    (7, 3): 24,
    (6, 10): 25,
    (7, 10): 26,
}

NLL2RDF_CLASSES = [
    "NO-CLASS",
    "B-PER-COMMERCIALIZE",
    "I-PER-COMMERCIALIZE",
    "B-PER-REPRODUCE",
    "I-PER-REPRODUCE",
    "B-PER-DERIVE",
    "I-PER-DERIVE",
    "B-PER-DISTRIBUTE",
    "I-PER-DISTRIBUTE",
    "B-PER-READ",
    "I-PER-READ",
    "B-PER-SELL",
    "I-PER-SELL",
    "B-PRO-COMMERCIALIZE",
    "I-PRO-COMMERCIALIZE",
    "B-PRO-DERIVE",
    "I-PRO-DERIVE",
    "B-PRO-DISTRIBUTE",
    "I-PRO-DISTRIBUTE",
    "B-REQ-ATTACHPOLICY",
    "I-REQ-ATTACHPOLICY",
    "B-REQ-ATTACHSOURCE",
    "I-REQ-ATTACHSOURCE",
    "B-REQ-ATTRIBUTE",
    "I-REQ-ATTRIBUTE",
    "B-REQ-SHAREALIKE",
    "I-REQ-SHAREALIKE",
]
